"""Add authentication models

Revision ID: c41d52d02da3
Revises: 17ea91610659
Create Date: 2026-01-18 15:22:55.327629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c41d52d02da3'
down_revision: Union[str, Sequence[str], None] = '17ea91610659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_conversation_topics_topic_id', 'conversation_topics', ['topic_id'], unique=False)
    op.drop_index(op.f('idx_conversations_is_saved'), table_name='conversations', postgresql_where='(is_saved = true)')
    op.drop_index(op.f('idx_conversations_source_lookup'), table_name='conversations', postgresql_where='(source_id IS NOT NULL)')
    op.drop_index(op.f('idx_conversations_created_at'), table_name='conversations')
    op.create_index('idx_conversations_created_at', 'conversations', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index(op.f('idx_conversations_updated_at'), table_name='conversations')
    op.create_index('idx_conversations_updated_at', 'conversations', [sa.literal_column('updated_at DESC')], unique=False)
    op.alter_column('jobs', 'kind',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('jobs', 'payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('jobs', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.drop_index(op.f('idx_jobs_not_before'), table_name='jobs', postgresql_where="(status = 'pending'::text)")
    op.drop_index(op.f('idx_jobs_created_at'), table_name='jobs')
    op.create_index('idx_jobs_created_at', 'jobs', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('message_embeddings', 'model',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_embeddings_vector_ivfflat'), table_name='message_embeddings', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('idx_embeddings_updated_at'), table_name='message_embeddings')
    op.create_index('idx_embeddings_updated_at', 'message_embeddings', [sa.literal_column('updated_at DESC')], unique=False)
    op.alter_column('messages', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_messages_fts'), table_name='messages', postgresql_using='gin')
    op.drop_index(op.f('idx_messages_source_lookup'), table_name='messages', postgresql_where='(source_message_id IS NOT NULL)')
    op.drop_index(op.f('idx_messages_trgm'), table_name='messages', postgresql_ops={'content': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_messages_conv_created'), table_name='messages')
    op.create_index('idx_messages_conv_created', 'messages', ['conversation_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_index(op.f('idx_messages_created_at'), table_name='messages')
    op.create_index('idx_messages_created_at', 'messages', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_topics_name', 'topics', ['name'], unique=False)
    op.add_column('users', sa.Column('us_totp_secrets', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('us_phone_number', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'us_phone_number')
    op.drop_column('users', 'us_totp_secrets')
    op.drop_index('idx_topics_name', table_name='topics')
    op.drop_index('idx_messages_created_at', table_name='messages')
    op.create_index(op.f('idx_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.drop_index('idx_messages_conv_created', table_name='messages')
    op.create_index(op.f('idx_messages_conv_created'), 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_messages_trgm'), 'messages', ['content'], unique=False, postgresql_ops={'content': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_messages_source_lookup'), 'messages', ['conversation_id', 'source_message_id'], unique=False, postgresql_where='(source_message_id IS NOT NULL)')
    op.create_index(op.f('idx_messages_fts'), 'messages', ['message_search'], unique=False, postgresql_using='gin')
    op.alter_column('messages', 'role',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index('idx_embeddings_updated_at', table_name='message_embeddings')
    op.create_index(op.f('idx_embeddings_updated_at'), 'message_embeddings', ['updated_at'], unique=False)
    op.create_index(op.f('idx_embeddings_vector_ivfflat'), 'message_embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('message_embeddings', 'model',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index('idx_jobs_created_at', table_name='jobs')
    op.create_index(op.f('idx_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('idx_jobs_not_before'), 'jobs', ['not_before'], unique=False, postgresql_where="(status = 'pending'::text)")
    op.alter_column('jobs', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('jobs', 'payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('jobs', 'kind',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index('idx_conversations_updated_at', table_name='conversations')
    op.create_index(op.f('idx_conversations_updated_at'), 'conversations', ['updated_at'], unique=False)
    op.drop_index('idx_conversations_created_at', table_name='conversations')
    op.create_index(op.f('idx_conversations_created_at'), 'conversations', ['created_at'], unique=False)
    op.create_index(op.f('idx_conversations_source_lookup'), 'conversations', ['source_type', 'source_id'], unique=True, postgresql_where='(source_id IS NOT NULL)')
    op.create_index(op.f('idx_conversations_is_saved'), 'conversations', ['is_saved'], unique=False, postgresql_where='(is_saved = true)')
    op.drop_index('idx_conversation_topics_topic_id', table_name='conversation_topics')
    # ### end Alembic commands ###
